### ISSUE TITLE
add batton gen public key in form new server

### ISSUE THREAD

**Issue by pomazanbohdan** [whyvra/tunnel#2]
![image](https://user-images.githubusercontent.com/696713/104021348-469d7c80-51c7-11eb-9df1-c092a5194aee.png)

**Comment by whyvra** [comment]
As stated in the README, tunnel is not meant to manage your server's private key. A random public key will be of no use if you don't have the associated private key.

The approach here is to generate a private key on your server using `wg genkey > privatekey` making sure to set the appropriate permissions on the `privatekey` file beforehand.  You can then use `wg pubkey < privatekey` to print out the associated public key. This is what you should input in tunnel.
