### ISSUE TITLE
error in start over revers-proxy

### ISSUE THREAD

**Issue by pomazanbohdan** [whyvra/tunnel#6]
https://wg.pomazan.xyz/

![image](https://user-images.githubusercontent.com/696713/104025800-d514fc80-51cd-11eb-82b8-1ab7a6665719.png)

**Comment by whyvra** [comment]
Could you please provide more info on your setup.  This seems like an issue with your reverse proxy.

- Are you using only the default image or are you running behind Traefik?
- Is the reverse proxy logging any kind of error?

I know that for nginx, you have to add a specific MIME for Web Assembly (as shown in the link provided below)
[https://github.com/whyvra/tunnel/blob/master/docker/nginx.conf#L28](https://github.com/whyvra/tunnel/blob/master/docker/nginx.conf#L28)

**Comment by whyvra** [comment]
The issue is with you `appsettings.json` file. It's not valid. There's a missing comma at the end of line 7.
