### ISSUE TITLE
docker run statup message misleading

### ISSUE THREAD

**Issue by 0xErnie** [whyvra/tunnel#8]
### Description

When using docker run as decribed in the Readme, the output of the command suggests, that the service is running on port 5000.

### Current Behavior
```
$ docker run -it --rm -p "5800:5800" whyvra/tunnel
[11:12:53 WRN] Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Cannot assign requested address'.
[11:12:53 INF] Now listening on: http://localhost:5000
[11:12:53 INF] Application started. Press Ctrl+C to shut down.
[11:12:53 INF] Hosting environment: Production
[11:12:53 INF] Content root path: /srv/dotnet
```

### Expected Behavior
`[11:12:53 INF] Now listening on: http://localhost:5800`

### Steps to Reproduce
1. docker run -it --rm -p "5800:5800" whyvra/tunnel

### Context (Environment)
MacOS 12.0.1 (21A559)
Docker version 20.10.7, build f0df350

**Comment by whyvra** [comment]
This is because the API service is actually running on port 5000 but it's being reverse-proxied by nginx in order to serve everything under the same URL.

There might be a way to swallow that log message. I will look into it

**Comment by whyvra** [comment]
Hi,

I made some changes to the appsettings.json file for the web API project. Messages related to port bindings should no longer appear in the console. They will remain in the JSON log file as it could be useful when debugging issues.

Cheers!
